<Project Sdk="Aspire.AppHost.Sdk/13.3.3">

  <ItemGroup>
    <ProjectReference Include="..\HelpDesk.API\HelpDesk.API.csproj" />
    <ProjectReference Include="..\HelpDesk.Web\HelpDesk.Web.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.3.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>46aa97dc-5967-4740-b085-d50f604e82d6</UserSecretsId>
  </PropertyGroup>

</Project>
